# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=10)),
                ('has_cancelled', models.BooleanField()),
                ('bus_time', models.CharField(max_length=1)),
                ('destination', models.CharField(max_length=1)),
                ('date_of_bus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('bhavan', models.CharField(max_length=20)),
                ('cost_list_looters', models.CharField(max_length=1000)),
                ('cost_list_mess', models.CharField(max_length=1000)),
                ('cost_list_fk', models.CharField(max_length=1000)),
                ('cost_list_anc', models.CharField(max_length=1000)),
                ('cost_list_others', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
