# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_cost_bitsian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
